#!/bin/bash

# Script to add required files to Messages Extension target in Xcode project
# This fixes the archive build errors related to missing symbols

PROJECT_FILE="macadamia.xcodeproj/project.pbxproj"
BACKUP_FILE="macadamia.xcodeproj/project.pbxproj.backup"

echo "Creating backup of project file..."
cp "$PROJECT_FILE" "$BACKUP_FILE"

echo "IMPORTANT: The real issue is MISSING SWIFT PACKAGE DEPENDENCIES!"
echo ""
echo "The files already have target membership set, but the Messages Extension"
echo "is missing critical Swift Package dependencies."
echo ""
echo "Swift Packages that need to be added to macadamiaMessages target:"
echo "=================================================================="
echo ""
echo "REQUIRED Package Dependencies:"
echo "   - secp256k1 (from swift-secp256k1) - Used by PersistentModelV1.swift"
echo "   - BIP39 (from BIP39 package) - Used by restore.swift"
echo ""
echo "ALREADY LINKED:"
echo "   - CashuSwift ✓"
echo ""
echo "Verify these files have target membership (should already be set):"
echo "=================================================================="
echo "   - PersistentModelV1/PersistentModelV1.swift"
echo "   - PersistentModelV1/EventFactory.swift" 
echo "   - PersistentModelV1/Mint.swift"
echo "   - PersistentModelV1/Operations/send.swift"
echo "   - PersistentModelV1/Operations/inputSelection.swift"
echo "   - Misc/ActionButton.swift"
echo "   - Misc/Currency.swift"
echo "   - Wallet/Redeem/RedeemView.swift"
echo "   - Misc/TokenText.swift"
echo ""
echo "Steps to fix in Xcode:"
echo "====================="
echo "1. Open macadamia.xcodeproj in Xcode"
echo "2. Select the 'macadamiaMessages' target"
echo "3. Go to the 'General' tab"
echo "4. Scroll to 'Frameworks and Libraries' section"
echo "5. Click the '+' button"
echo "6. Add these package products:"
echo "   - secp256k1 (from swift-secp256k1)"
echo "   - BIP39 (from BIP39)" 
echo "7. Clean Build Folder (⇧⌘K)"
echo "8. Try archiving again"
echo ""
echo "Alternative Build Settings Fix (if adding files doesn't work):"
echo "=============================================================="
echo "1. Select the macadamiaMessages target"
echo "2. Go to Build Settings tab"
echo "3. Search for 'Swift Compiler - Code Generation'"
echo "4. Change 'Compilation Mode' from 'Whole Module' to 'Incremental' for Release"
echo "5. This is less optimal but can help diagnose the issue"
echo ""
echo "Backup created at: $BACKUP_FILE"
